# Create Cloudflare Tunnel, route DNS, and write cloudflare/config.yml
param(
    [string]$TunnelName = 'pawnode-stream',
    [string]$Hostname = 'stream.pawdomain.com',
    [string]$ApiHostname = 'api.pawdomain.com',
    [string]$Go2rtcUrl = 'http://127.0.0.1:1984',
    [string]$PawnodeApiUrl = 'http://127.0.0.1:3000'
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$scriptsDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$cfDir = Join-Path $root 'cloudflare'
$exePath = Join-Path $cfDir 'cloudflared.exe'
$configPath = Join-Path $cfDir 'config.yml'
$envFile = Join-Path $root '.env'
$setupScript = Join-Path $scriptsDir 'setup-cloudflared.ps1'
$loginScript = Join-Path $scriptsDir 'login-cloudflare.ps1'
$certPath = Join-Path $env:USERPROFILE '.cloudflared\cert.pem'

function Get-CloudflaredExe {
    if (-not (Test-Path $exePath)) {
        Write-Host 'cloudflared.exe not found. Running setup-cloudflared.ps1...'
        & $setupScript
    }
    if (-not (Test-Path $exePath)) {
        Write-Error "cloudflared.exe missing: $exePath"
        exit 1
    }
    return $exePath
}

function Get-TunnelJson($cf, $name) {
    $raw = & $cf tunnel list --output json 2>$null
    if (-not $raw) {
        return $null
    }
    $items = $raw | ConvertFrom-Json
    return $items | Where-Object { $_.name -eq $name } | Select-Object -First 1
}

$cf = Get-CloudflaredExe

if (-not (Test-Path $certPath)) {
    Write-Host 'Cloudflare login required.'
    & $loginScript
}

Write-Host "Creating tunnel: $TunnelName"
$existing = Get-TunnelJson $cf $TunnelName
if ($existing) {
    Write-Host "Tunnel already exists: $($existing.id)"
    $tunnelId = $existing.id
} else {
    $createOut = & $cf tunnel create $TunnelName 2>&1 | Out-String
    Write-Host $createOut.Trim()
    $existing = Get-TunnelJson $cf $TunnelName
    if (-not $existing) {
        Write-Error "Failed to create or locate tunnel: $TunnelName"
        exit 1
    }
    $tunnelId = $existing.id
}

$credFile = Join-Path $env:USERPROFILE ".cloudflared\$tunnelId.json"
if (-not (Test-Path $credFile)) {
    Write-Error "Credentials file not found: $credFile"
    exit 1
}

Write-Host "Routing DNS: $Hostname -> $TunnelName"
$dnsOut = & $cf tunnel route dns $TunnelName $Hostname 2>&1 | Out-String
Write-Host $dnsOut.Trim()

Write-Host "Routing DNS: $ApiHostname -> $TunnelName"
$apiDnsOut = & $cf tunnel route dns $TunnelName $ApiHostname 2>&1 | Out-String
Write-Host $apiDnsOut.Trim()

$go2rtcService = $Go2rtcUrl.TrimEnd('/')
$pawnodeService = $PawnodeApiUrl.TrimEnd('/')

$config = @"
# PawNode — go2rtc HLS + PawNode API via Cloudflare Tunnel
# Generated by scripts/create-tunnel.ps1

tunnel: $TunnelName
credentials-file: $credFile

ingress:
  - hostname: $Hostname
    service: $go2rtcService
    originRequest:
      noTLSVerify: true
  - hostname: $ApiHostname
    service: $pawnodeService
    originRequest:
      noTLSVerify: true
  - service: http_status:404
"@

Set-Content -Path $configPath -Value $config -Encoding UTF8
Write-Host ''
Write-Host "Wrote $configPath"

$streamName = 'tapo'
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*GO2RTC_STREAM_NAME=(.*)$') {
            $val = $matches[1].Trim().Trim('"')
            if ($val -ne '') {
                $script:streamName = $val
            }
        }
    }
}

$hlsUrl = "https://$Hostname/api/stream.m3u8?src=$streamName"
Write-Host ''
Write-Host '=== Tunnel ready ==='
Write-Host "Tunnel ID : $tunnelId"
Write-Host "Hostname  : $Hostname"
Write-Host "API host  : $ApiHostname"
Write-Host "go2rtc    : $go2rtcService"
Write-Host "PawNode   : $pawnodeService"
Write-Host ''
Write-Host 'HLS URL (wp-config.php):'
Write-Host $hlsUrl
Write-Host ''
Write-Host 'PawNode API URL (wp-config.php):'
Write-Host "  define( 'PAWNODE_API_URL', 'https://$ApiHostname' );"
Write-Host ''
Write-Host 'Start tunnel:'
Write-Host '  powershell -ExecutionPolicy Bypass -File scripts/start-tunnel.ps1'
Write-Host ''
Write-Host 'wp-config.php:'
Write-Host "  define( 'PAWNODE_HLS_URL', '$hlsUrl' );"

# Update .env HLS_PUBLIC_URL if file exists
if (Test-Path $envFile) {
    $lines = Get-Content $envFile
    $updated = $false
    $newLines = foreach ($line in $lines) {
        if ($line -match '^\s*HLS_PUBLIC_URL=') {
            $updated = $true
            "HLS_PUBLIC_URL=$hlsUrl"
        } else {
            $line
        }
    }
    if (-not $updated) {
        $newLines += "HLS_PUBLIC_URL=$hlsUrl"
    }
    Set-Content -Path $envFile -Value $newLines -Encoding UTF8
    Write-Host ''
    Write-Host "Updated .env HLS_PUBLIC_URL"
}
